name: ci

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  Test:
    strategy:
      matrix:
        lua-version: ["5.4", "5.3", "5.2", "5.1", "luajit"]
        os: ["ubuntu-latest"]
        include:
          - os: "macos-latest"
            lua-version: "5.4"
          # - os: "windows-latest"
          #  lua-version: "luajit"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master
      - uses: hishamhm/gh-actions-lua@master
        with:
          luaVersion: ${{ matrix.lua-version }}
      - uses: hishamhm/gh-actions-luarocks@master
      - name: Test
        run: |
          make dev
          make
